title: 'The basics of GitHub part 1: Repositories'
description: 'Here you will learn, well, just look at the title!'
template:
  repo: the-basics-of-github-template
  name: the-basics-of-github-part-1
  description: A Learning Lab course on the basics of GitHub
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
  - type: updateBranchProtection
    branch: master
    enforce_admins: true
steps:
  - title: Make a comment
    description: 'Simple step, but vital for issues and pull requests (PRs)'
    event: issue_comment.created
    link: '{{ repoUrl }}'
